// [2026-03-27] [LogPanel] - Added Log Parser utility to process raw streams generated by debug dump

export interface ParsedLog {
    content: string;
    thinking: string;
    stats: {
        contentLength: number;
        thinkingLength: number;
    }
}

export function parseRawLog(fileContent: string): ParsedLog {
    const lines = fileContent.split('\n');
    let fullContent = '';
    let fullThinking = '';

    lines.forEach(line => {
        let cleanLine = line.trim();
        if (!cleanLine) return;

        // Remove SSE marker
        if (cleanLine.startsWith('data:')) {
            cleanLine = cleanLine.replace(/^data:\s*/, '');
        }

        if (cleanLine === '<DONE/>') return;

        try {
            const json = JSON.parse(cleanLine);
            const delta = json.choices?.[0]?.delta || json.delta || json;

            // Extract content
            if (delta.content) fullContent += delta.content;

            // Extract reasoning
            const thinking = delta.reasoning_content || delta.thinking || delta.reasoning;
            if (thinking) fullThinking += thinking;

            // Extract message fields (fallback format)
            if (json.message) {
                if (json.message.content) fullContent += json.message.content;
                const msgThinking = json.message.thinking || json.message.reasoning_content;
                if (msgThinking) fullThinking += msgThinking;
            }

            // Extract text completions
            const text = json.choices?.[0]?.text || json.text;
            if (text && !delta.content) {
                if (typeof text === 'string') fullContent += text;
            }
        } catch (e) {
            // ignore non-json
        }
    });

    return {
        content: fullContent,
        thinking: fullThinking,
        stats: {
            contentLength: fullContent.length,
            thinkingLength: fullThinking.length
        }
    };
}
